-- FTS Selfie Event advertising analytics v13

create table if not exists public.fts_event_ad_events_v13 (
  id bigint generated by default as identity primary key,
  event_token text not null,
  ad_key text not null,
  ad_name text not null default 'Werbung',
  action text not null check (action in ('view','click')),
  session_id text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists fts_event_ad_events_v13_event_idx
  on public.fts_event_ad_events_v13(event_token, created_at);
create index if not exists fts_event_ad_events_v13_ad_idx
  on public.fts_event_ad_events_v13(event_token, ad_key, action);

-- One counted banner view per browser session and ad.
create unique index if not exists fts_event_ad_events_v13_unique_view
  on public.fts_event_ad_events_v13(event_token, ad_key, session_id)
  where action='view' and session_id<>'';

create table if not exists public.fts_analytics_meta_v13 (
  key text primary key,
  started_at timestamptz not null default now()
);

insert into public.fts_analytics_meta_v13(key)
values('ad_tracking')
on conflict(key) do nothing;

alter table public.fts_event_ad_events_v13 enable row level security;
alter table public.fts_analytics_meta_v13 enable row level security;

revoke all on public.fts_event_ad_events_v13 from anon, authenticated;
revoke all on public.fts_analytics_meta_v13 from anon, authenticated;

drop policy if exists "no direct browser access to ad analytics" on public.fts_event_ad_events_v13;
create policy "no direct browser access to ad analytics"
on public.fts_event_ad_events_v13 for all to anon, authenticated
using(false) with check(false);

drop policy if exists "no direct browser access to analytics meta" on public.fts_analytics_meta_v13;
create policy "no direct browser access to analytics meta"
on public.fts_analytics_meta_v13 for all to anon, authenticated
using(false) with check(false);

create or replace function public.fts_admin_event_ad_stats_v13(
  p_admin_code text,
  p_event_token text
)
returns table(
  ad_key text,
  ad_name text,
  views bigint,
  clicks bigint,
  unique_clickers bigint,
  click_rate numeric
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists (
    select 1 from public.fts_admin_dashboard_events(p_admin_code) d
    where d.event_token::text=p_event_token::text
  ) then
    raise exception 'Not authorized for this event';
  end if;

  return query
  with agg as (
    select
      a.ad_key,
      max(a.ad_name) filter(where a.ad_name<>'') as ad_name,
      count(*) filter(where a.action='view')::bigint as views,
      count(*) filter(where a.action='click')::bigint as clicks,
      count(distinct nullif(a.session_id,'')) filter(where a.action='click')::bigint as unique_clickers
    from public.fts_event_ad_events_v13 a
    where a.event_token=p_event_token::text
    group by a.ad_key
  )
  select
    x.ad_key,
    coalesce(nullif(x.ad_name,''),'Werbung') as ad_name,
    x.views,
    x.clicks,
    x.unique_clickers,
    case when x.views>0 then round((x.unique_clickers::numeric/x.views::numeric)*100,1) else 0 end
  from agg x
  order by x.clicks desc,x.views desc,x.ad_name;
end;
$$;

create or replace function public.fts_admin_event_ad_daily_v13(
  p_admin_code text,
  p_event_token text
)
returns table(
  ad_key text,
  ad_name text,
  stat_day date,
  views bigint,
  clicks bigint
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists (
    select 1 from public.fts_admin_dashboard_events(p_admin_code) d
    where d.event_token::text=p_event_token::text
  ) then
    raise exception 'Not authorized for this event';
  end if;

  return query
  select
    a.ad_key,
    max(a.ad_name) filter(where a.ad_name<>'') as ad_name,
    timezone('Europe/Luxembourg',a.created_at)::date as stat_day,
    count(*) filter(where a.action='view')::bigint as views,
    count(*) filter(where a.action='click')::bigint as clicks
  from public.fts_event_ad_events_v13 a
  where a.event_token=p_event_token::text
  group by a.ad_key, timezone('Europe/Luxembourg',a.created_at)::date
  order by stat_day,a.ad_key;
end;
$$;

create or replace function public.fts_get_shared_event_report_v13(
  p_share_token text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_event_token text;
  v_base jsonb;
  v_ads jsonb;
  v_started_at timestamptz;
begin
  v_base := public.fts_get_shared_event_report_v12(p_share_token);
  if v_base is null then return null; end if;

  select r.event_token into v_event_token
  from public.fts_event_report_shares_v12 r
  where r.share_token=p_share_token
    and r.enabled=true
    and r.expires_at>now()
  limit 1;

  select m.started_at into v_started_at
  from public.fts_analytics_meta_v13 m
  where m.key='ad_tracking';

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'ad_key',q.ad_key,
      'name',q.ad_name,
      'views',q.views,
      'clicks',q.clicks,
      'unique_clickers',q.unique_clickers,
      'click_rate',q.click_rate
    ) order by q.clicks desc,q.views desc,q.ad_name
  ),'[]'::jsonb)
  into v_ads
  from (
    select
      a.ad_key,
      coalesce(nullif(max(a.ad_name) filter(where a.ad_name<>''),''),'Werbung') as ad_name,
      count(*) filter(where a.action='view')::bigint as views,
      count(*) filter(where a.action='click')::bigint as clicks,
      count(distinct nullif(a.session_id,'')) filter(where a.action='click')::bigint as unique_clickers,
      case
        when count(*) filter(where a.action='view')>0
        then round(
          (count(distinct nullif(a.session_id,'')) filter(where a.action='click'))::numeric
          / (count(*) filter(where a.action='view'))::numeric * 100,1
        )
        else 0
      end as click_rate
    from public.fts_event_ad_events_v13 a
    where a.event_token=v_event_token
    group by a.ad_key
  ) q;

  return v_base
    || jsonb_build_object(
      'ad_tracking_started_at',v_started_at,
      'ads',v_ads
    );
end;
$$;

revoke all on function public.fts_admin_event_ad_stats_v13(text,text) from public;
revoke all on function public.fts_admin_event_ad_daily_v13(text,text) from public;
revoke all on function public.fts_get_shared_event_report_v13(text) from public;

grant execute on function public.fts_admin_event_ad_stats_v13(text,text) to anon,authenticated;
grant execute on function public.fts_admin_event_ad_daily_v13(text,text) to anon,authenticated;
grant execute on function public.fts_get_shared_event_report_v13(text) to anon,authenticated;
