-- FTS Selfie Event lifecycle + scan statistics v11
-- Apply this migration in Supabase SQL editor before merging the matching frontend branch.

create table if not exists public.fts_event_lifecycle_v11 (
  event_token text primary key,
  schedule jsonb not null default '[]'::jsonb,
  gallery_url text not null default '',
  gallery_available_at text not null default '',
  link_expires_at text not null default '',
  test_days_before integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.fts_event_scans_v11 (
  id bigint generated by default as identity primary key,
  event_token text not null,
  scanned_at timestamptz not null default now()
);

create index if not exists fts_event_scans_v11_event_token_idx
  on public.fts_event_scans_v11(event_token);
create index if not exists fts_event_scans_v11_scanned_at_idx
  on public.fts_event_scans_v11(scanned_at);

alter table public.fts_event_lifecycle_v11 enable row level security;
alter table public.fts_event_scans_v11 enable row level security;

revoke all on public.fts_event_lifecycle_v11 from anon, authenticated;
revoke all on public.fts_event_scans_v11 from anon, authenticated;

create or replace function public.fts_admin_set_event_lifecycle_v11(
  p_admin_code text,
  p_event_token text,
  p_schedule jsonb,
  p_gallery_url text default '',
  p_gallery_available_at text default '',
  p_link_expires_at text default '',
  p_test_days_before integer default 0
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.fts_admin_dashboard_events(p_admin_code) d
    where d.event_token::text = p_event_token::text
  ) then
    raise exception 'Not authorized for this event';
  end if;

  insert into public.fts_event_lifecycle_v11(
    event_token,schedule,gallery_url,gallery_available_at,link_expires_at,test_days_before,updated_at
  )
  values(
    p_event_token::text,
    coalesce(p_schedule,'[]'::jsonb),
    coalesce(p_gallery_url,''),
    coalesce(p_gallery_available_at,''),
    coalesce(p_link_expires_at,''),
    greatest(0,coalesce(p_test_days_before,0)),
    now()
  )
  on conflict(event_token) do update set
    schedule=excluded.schedule,
    gallery_url=excluded.gallery_url,
    gallery_available_at=excluded.gallery_available_at,
    link_expires_at=excluded.link_expires_at,
    test_days_before=excluded.test_days_before,
    updated_at=now();
end;
$$;

create or replace function public.fts_admin_get_event_lifecycle_v11(
  p_admin_code text,
  p_event_token text
)
returns table(
  schedule jsonb,
  gallery_url text,
  gallery_available_at text,
  link_expires_at text,
  test_days_before integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.fts_admin_dashboard_events(p_admin_code) d
    where d.event_token::text = p_event_token::text
  ) then
    raise exception 'Not authorized for this event';
  end if;

  return query
  select l.schedule,l.gallery_url,l.gallery_available_at,l.link_expires_at,l.test_days_before
  from public.fts_event_lifecycle_v11 l
  where l.event_token=p_event_token::text;
end;
$$;

create or replace function public.fts_get_event_lifecycle_v11(
  p_event_token text
)
returns table(
  schedule jsonb,
  gallery_url text,
  gallery_available_at text,
  link_expires_at text,
  test_days_before integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
begin
  select e.event_token::text into v_token
  from public.fts_get_event(p_event_token) e
  limit 1;

  if v_token is null then
    return;
  end if;

  return query
  select
    l.schedule,
    case
      when nullif(l.gallery_available_at,'') is not null
       and timezone('Europe/Luxembourg',now()) >= l.gallery_available_at::timestamp
      then l.gallery_url
      else ''
    end as gallery_url,
    l.gallery_available_at,
    l.link_expires_at,
    l.test_days_before
  from public.fts_event_lifecycle_v11 l
  where l.event_token=v_token;
end;
$$;

create or replace function public.fts_record_event_scan_v11(
  p_event_token text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
begin
  select e.event_token::text into v_token
  from public.fts_get_event(p_event_token) e
  limit 1;

  if v_token is null then
    return;
  end if;

  insert into public.fts_event_scans_v11(event_token) values(v_token);
end;
$$;

create or replace function public.fts_admin_event_scan_stats_v11(
  p_admin_code text
)
returns table(
  event_token text,
  scan_count bigint,
  scan_today bigint
)
language sql
security definer
set search_path = public
as $$
  with allowed as (
    select d.event_token::text as event_token
    from public.fts_admin_dashboard_events(p_admin_code) d
  ),
  agg as (
    select s.event_token,
           count(*)::bigint as scan_count,
           count(*) filter (
             where timezone('Europe/Luxembourg',s.scanned_at)::date =
                   timezone('Europe/Luxembourg',now())::date
           )::bigint as scan_today
    from public.fts_event_scans_v11 s
    group by s.event_token
  )
  select a.event_token,coalesce(g.scan_count,0),coalesce(g.scan_today,0)
  from allowed a
  left join agg g using(event_token);
$$;

create or replace function public.fts_admin_event_scan_daily_v11(
  p_admin_code text,
  p_event_token text
)
returns table(
  scan_day date,
  scan_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.fts_admin_dashboard_events(p_admin_code) d
    where d.event_token::text = p_event_token::text
  ) then
    raise exception 'Not authorized for this event';
  end if;

  return query
  select timezone('Europe/Luxembourg',s.scanned_at)::date as scan_day,
         count(*)::bigint
  from public.fts_event_scans_v11 s
  where s.event_token=p_event_token::text
  group by 1
  order by 1;
end;
$$;

create or replace function public.fts_register_photo_v11(
  p_event_token text,
  p_original_path text,
  p_designed_path text,
  p_guest_session_id text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
  v_lifecycle public.fts_event_lifecycle_v11%rowtype;
  v_now_local timestamp without time zone := timezone('Europe/Luxembourg',now());
  v_first_date date;
  v_first_start time;
  v_allowed boolean := false;
  v_photo_id uuid;
begin
  select e.event_token::text into v_token
  from public.fts_get_event(p_event_token) e
  limit 1;

  if v_token is null then
    raise exception 'Event not found';
  end if;

  select * into v_lifecycle
  from public.fts_event_lifecycle_v11
  where event_token=v_token;

  -- Legacy events without lifecycle metadata keep their existing behavior.
  if not found then
    select public.fts_register_photo_v10(
      p_event_token,p_original_path,p_designed_path,p_guest_session_id
    ) into v_photo_id;
    return v_photo_id;
  end if;

  select exists(
    select 1
    from jsonb_array_elements(coalesce(v_lifecycle.schedule,'[]'::jsonb)) x
    where v_now_local::date=(x->>'date')::date
      and v_now_local::time >= coalesce(nullif(x->>'start',''),'00:00')::time
      and v_now_local::time <= coalesce(nullif(x->>'end',''),'23:59')::time
  ) into v_allowed;

  if not v_allowed and v_lifecycle.test_days_before>0 then
    select (x->>'date')::date,
           coalesce(nullif(x->>'start',''),'00:00')::time
      into v_first_date,v_first_start
    from jsonb_array_elements(coalesce(v_lifecycle.schedule,'[]'::jsonb)) x
    order by (x->>'date')::date, coalesce(nullif(x->>'start',''),'00:00')::time
    limit 1;

    if v_first_date is not null
       and v_now_local::date >= (v_first_date-v_lifecycle.test_days_before)
       and (
         v_now_local::date < v_first_date
         or (v_now_local::date=v_first_date and v_now_local::time < v_first_start)
       )
    then
      v_allowed := true;
    end if;
  end if;

  if not v_allowed then
    raise exception 'Uploads are closed for this event';
  end if;

  select public.fts_register_photo_v10(
    p_event_token,p_original_path,p_designed_path,p_guest_session_id
  ) into v_photo_id;
  return v_photo_id;
end;
$$;

revoke all on function public.fts_get_event_lifecycle_v11(text) from public;
revoke all on function public.fts_record_event_scan_v11(text) from public;
revoke all on function public.fts_register_photo_v11(text,text,text,text) from public;
revoke all on function public.fts_admin_set_event_lifecycle_v11(text,text,jsonb,text,text,text,integer) from public;
revoke all on function public.fts_admin_get_event_lifecycle_v11(text,text) from public;
revoke all on function public.fts_admin_event_scan_stats_v11(text) from public;
revoke all on function public.fts_admin_event_scan_daily_v11(text,text) from public;

grant execute on function public.fts_get_event_lifecycle_v11(text) to anon, authenticated;
grant execute on function public.fts_record_event_scan_v11(text) to anon, authenticated;
grant execute on function public.fts_register_photo_v11(text,text,text,text) to anon, authenticated;
grant execute on function public.fts_admin_set_event_lifecycle_v11(text,text,jsonb,text,text,text,integer) to anon, authenticated;
grant execute on function public.fts_admin_get_event_lifecycle_v11(text,text) to anon, authenticated;
grant execute on function public.fts_admin_event_scan_stats_v11(text) to anon, authenticated;
grant execute on function public.fts_admin_event_scan_daily_v11(text,text) to anon, authenticated;
