-- FTS Selfie Event system check + issue log v14

create table if not exists public.fts_event_issues_v14 (
  id bigint generated by default as identity primary key,
  event_token text not null,
  issue_type text not null,
  severity text not null default 'warning' check (severity in ('info','warning','error')),
  message text not null,
  details jsonb not null default '{}'::jsonb,
  session_id text not null default '',
  fingerprint text not null default '',
  occurrences integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists fts_event_issues_v14_event_open_idx
  on public.fts_event_issues_v14(event_token,last_seen_at desc)
  where resolved_at is null;

create index if not exists fts_event_issues_v14_open_idx
  on public.fts_event_issues_v14(last_seen_at desc)
  where resolved_at is null;

alter table public.fts_event_issues_v14 enable row level security;
revoke all on public.fts_event_issues_v14 from anon, authenticated;

drop policy if exists "no direct browser access to event issues" on public.fts_event_issues_v14;
create policy "no direct browser access to event issues"
on public.fts_event_issues_v14 for all to anon, authenticated
using(false) with check(false);

create or replace function public.fts_admin_event_issues_v14(
  p_admin_code text,
  p_event_token text default null
)
returns table(
  issue_id bigint,
  event_token text,
  event_title text,
  issue_type text,
  severity text,
  message text,
  details jsonb,
  occurrences integer,
  first_seen_at timestamptz,
  last_seen_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.fts_selfie_admin_ok(p_admin_code) then
    raise exception 'Ungültiger Gerätezugang/Admin-Code';
  end if;

  return query
  select
    i.id,
    i.event_token,
    coalesce(e.title,'Unbekanntes Event'),
    i.issue_type,
    i.severity,
    i.message,
    i.details,
    i.occurrences,
    i.first_seen_at,
    i.last_seen_at
  from public.fts_event_issues_v14 i
  left join public.fts_selfie_events e on e.token=i.event_token
  where i.resolved_at is null
    and (p_event_token is null or i.event_token=p_event_token)
  order by
    case i.severity when 'error' then 1 when 'warning' then 2 else 3 end,
    i.last_seen_at desc;
end;
$$;

create or replace function public.fts_admin_resolve_event_issue_v14(
  p_admin_code text,
  p_issue_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.fts_selfie_admin_ok(p_admin_code) then
    raise exception 'Ungültiger Gerätezugang/Admin-Code';
  end if;

  update public.fts_event_issues_v14
  set resolved_at=now()
  where id=p_issue_id and resolved_at is null;

  return found;
end;
$$;

revoke all on function public.fts_admin_event_issues_v14(text,text) from public;
revoke all on function public.fts_admin_resolve_event_issue_v14(text,bigint) from public;
grant execute on function public.fts_admin_event_issues_v14(text,text) to anon,authenticated;
grant execute on function public.fts_admin_resolve_event_issue_v14(text,bigint) to anon,authenticated;
