import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const cors={
  "Access-Control-Allow-Origin":"*",
  "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods":"GET,POST,OPTIONS",
};
const UNIT_PRICE_CENTS=200;
const CURRENCY="EUR";
const MAX_TOTAL_QTY=50;
const tokenCache=new Map<string,{token:string;expiresAt:number}>();

type PayPalEnv="sandbox"|"live";
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}})}
function clean(v:unknown,max=300){return String(v??"").trim().slice(0,max)}
function centsToValue(cents:number){return (cents/100).toFixed(2)}
function valueToCents(v:unknown){const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?Math.round(n*100):NaN}
function normalizeEnv(v:unknown):PayPalEnv{return String(v||"").toLowerCase()==="live"?"live":"sandbox"}
function paypalBase(env:PayPalEnv){return env==="sandbox"?"https://api-m.sandbox.paypal.com":"https://api-m.paypal.com"}
function envName(env:PayPalEnv,base:string){return `PAYPAL_SELFIE_${env.toUpperCase()}_${base}`}
function paypalClientId(env:PayPalEnv){return Deno.env.get(envName(env,"CLIENT_ID"))||""}
function paypalSecret(env:PayPalEnv){return Deno.env.get(envName(env,"CLIENT_SECRET"))||""}
function paypalWebhookId(env:PayPalEnv){return Deno.env.get(envName(env,"WEBHOOK_ID"))||""}
function supabaseAdminKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS")||"";if(raw){try{const keys=JSON.parse(raw);if(keys?.default)return String(keys.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}

async function paypalAccessToken(env:PayPalEnv){
  const cached=tokenCache.get(env);if(cached&&Date.now()<cached.expiresAt-60_000)return cached.token;
  const id=paypalClientId(env),secret=paypalSecret(env);if(!id||!secret)throw new Error(`PayPal ${env==="live"?"Live":"Sandbox"} Secrets fehlen`);
  const r=await fetch(paypalBase(env)+"/v1/oauth2/token",{method:"POST",headers:{"Authorization":"Basic "+btoa(`${id}:${secret}`),"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"});
  const data=await r.json().catch(()=>({}));if(!r.ok||!data?.access_token)throw new Error(`PayPal ${env==="live"?"Live":"Sandbox"} OAuth fehlgeschlagen`);
  const entry={token:String(data.access_token),expiresAt:Date.now()+Math.max(60,Number(data.expires_in||300))*1000};tokenCache.set(env,entry);return entry.token;
}
async function paypalFetch(env:PayPalEnv,path:string,init:RequestInit={}){
  const token=await paypalAccessToken(env);const r=await fetch(paypalBase(env)+path,{...init,headers:{"Authorization":"Bearer "+token,"Content-Type":"application/json",...(init.headers||{})}});
  const txt=await r.text();let data:any={};try{data=txt?JSON.parse(txt):{}}catch{data={raw:txt}};
  if(!r.ok){const err=new Error(data?.message||data?.name||`PayPal HTTP ${r.status}`);(err as any).paypal=data;(err as any).status=r.status;throw err}return data;
}
async function bodyOf(req:Request){if(req.method==="GET")return Object.fromEntries(new URL(req.url).searchParams.entries());return await req.json().catch(()=>({}))}
async function findEvent(admin:any,input:string){
  let q=await admin.from("fts_selfie_events").select("id,token,short_code,title,active,archived_at,expires_at").eq("token",input).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data;
  q=await admin.from("fts_selfie_events").select("id,token,short_code,title,active,archived_at,expires_at").eq("short_code",input.toUpperCase()).maybeSingle();if(q.error)throw q.error;return q.data;
}
async function eventSetting(admin:any,eventId:string){const {data,error}=await admin.from("fts_selfie_print_settings").select("enabled,print_starts_at,print_ends_at,unit_price_cents,currency,paypal_environment,billing_mode,organizer_flat_price_cents").eq("event_id",eventId).maybeSingle();if(error)throw error;return data}
function windowActive(setting:any){if(!setting?.enabled)return false;if(Number(setting.unit_price_cents||UNIT_PRICE_CENTS)!==UNIT_PRICE_CENTS)return false;if(String(setting.currency||CURRENCY).toUpperCase()!==CURRENCY)return false;const now=Date.now(),start=setting.print_starts_at?Date.parse(setting.print_starts_at):NaN,end=setting.print_ends_at?Date.parse(setting.print_ends_at):NaN;if(Number.isFinite(start)&&now<start)return false;if(Number.isFinite(end)&&now>end)return false;return true}
async function ownedOrder(admin:any,orderId:string,eventId:string,sessionId:string){const {data,error}=await admin.from("fts_selfie_print_orders").select("*").eq("id",orderId).eq("event_id",eventId).eq("guest_session_id",sessionId).maybeSingle();if(error)throw error;return data}
async function receiptForOrder(admin:any,orderId:string){const {data,error}=await admin.from("fts_selfie_receipts").select("receipt_number,event_title_snapshot,organizer_snapshot,event_date_snapshot,quantity_total,unit_price_cents,total_cents,refund_cents,currency,payment_method,paypal_order_id,paypal_capture_id,payment_status,paid_at,items_snapshot").eq("order_id_snapshot",orderId).maybeSingle();if(error)throw error;return data}
function safeReceipt(r:any){if(!r)return null;return {receipt_number:r.receipt_number,event_title:r.event_title_snapshot,organizer_name:r.organizer_snapshot,event_date:r.event_date_snapshot,quantity_total:r.quantity_total,unit_price_cents:r.unit_price_cents,total_cents:r.total_cents,refund_cents:r.refund_cents||0,net_cents:Number(r.total_cents||0)-Number(r.refund_cents||0),currency:r.currency,payment_method:r.payment_method,paypal_order_id:r.paypal_order_id||null,paypal_capture_id:r.paypal_capture_id||null,payment_status:r.payment_status,paid_at:r.paid_at,items:Array.isArray(r.items_snapshot)?r.items_snapshot:[]}}
function safeOrderStatus(o:any){return {order_id:o.id,billing_mode:o.billing_mode||"guest_paypal",paypal_environment:o.paypal_environment||null,paypal_order_id:o.paypal_order_id||null,payment_status:o.payment_status,print_status:o.print_status,quantity_total:o.quantity_total,total_cents:o.total_cents,total:centsToValue(Number(o.total_cents||0)),currency:o.currency,paid_at:o.paid_at||null,printed_at:o.printed_at||null}}
function paypalCapture(data:any){return data?.purchase_units?.[0]?.payments?.captures?.[0]||null}
async function fetchPayPalOrder(env:PayPalEnv,orderId:string){return await paypalFetch(env,"/v2/checkout/orders/"+encodeURIComponent(orderId),{method:"GET",headers:{"Prefer":"return=representation"}})}
function normalizeItems(rawItems:any[]){if(!Array.isArray(rawItems)||!rawItems.length||rawItems.length>20)throw new Error("Bitte mindestens ein Foto auswählen");const normalized=new Map<string,number>();for(const raw of rawItems){const id=clean(raw?.photo_id,80),qty=Number(raw?.quantity);if(!/^[0-9a-f-]{36}$/i.test(id)||!Number.isInteger(qty)||qty<1||qty>20)throw new Error("Ungültige Foto-Auswahl oder Anzahl");normalized.set(id,(normalized.get(id)||0)+qty)}const ids=[...normalized.keys()],quantityTotal=[...normalized.values()].reduce((a,b)=>a+b,0);if(quantityTotal<1||quantityTotal>MAX_TOTAL_QTY)throw new Error("Maximal 50 Ausdrucke pro Auftrag");return {normalized,ids,quantityTotal}}
async function validatePhotos(admin:any,eventId:string,sessionId:string,ids:string[],env:PayPalEnv){let q=admin.from("fts_selfie_photos").select("id,designed_path,event_id,guest_session_id,is_test,trashed_at").in("id",ids).eq("event_id",eventId).eq("guest_session_id",sessionId).is("trashed_at",null);if(env==="live")q=q.eq("is_test",false);const {data,error}=await q;if(error)throw error;if((data||[]).length!==ids.length||(data||[]).some((p:any)=>!p.designed_path))throw new Error("Mindestens ein Foto ist nicht für den Druck verfügbar");return data||[]}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(!["GET","POST"].includes(req.method))return json({ok:false,error:"Method not allowed"},405);
  try{
    const supabaseUrl=Deno.env.get("SUPABASE_URL"),adminKey=supabaseAdminKey();if(!supabaseUrl||!adminKey)throw new Error("Supabase Server-Konfiguration fehlt");
    const admin=createClient(supabaseUrl,adminKey,{auth:{persistSession:false,autoRefreshToken:false}}),body:any=await bodyOf(req);
    const action=clean(body.action,40)||"config",eventInput=clean(body.event_token,140),sessionId=clean(body.guest_session_id,140);if(!eventInput||!sessionId)return json({ok:false,error:"Event oder Gast-Sitzung fehlt"},400);
    const event=await findEvent(admin,eventInput);if(!event?.id||event.active!==true||event.archived_at)return json({ok:false,error:"Event nicht verfügbar"},404);
    const setting=await eventSetting(admin,event.id),active=windowActive(setting),billingMode=String(setting?.billing_mode||"guest_paypal"),env=normalizeEnv(setting?.paypal_environment),configured=!!(paypalClientId(env)&&paypalSecret(env));
    if(action==="config")return json({ok:true,enabled:active,configured,webhook_configured:!!paypalWebhookId(env),environment:env,client_id:configured&&billingMode==="guest_paypal"?paypalClientId(env):"",unit_price_cents:UNIT_PRICE_CENTS,unit_price:"2.00",currency:CURRENCY,billing_mode:billingMode,guest_payment_required:billingMode==="guest_paypal",covered_by_organizer:billingMode==="organizer_flat",fts_free:billingMode==="fts_free",starts_at:setting?.print_starts_at||null,ends_at:setting?.print_ends_at||null});
    if(!active)return json({ok:false,error:"Fotodruck ist für dieses Event gerade nicht freigeschaltet"},403);

    if(action==="create-covered-order"){
      if(!["organizer_flat","fts_free"].includes(billingMode))return json({ok:false,error:"Dieser Event verlangt eine Gastzahlung"},409);
      const {normalized,ids,quantityTotal}=normalizeItems(Array.isArray(body.items)?body.items:[]),photos=await validatePhotos(admin,event.id,sessionId,ids,env),paymentStatus=billingMode==="organizer_flat"?"COVERED":"FREE";
      const {data:order,error:orderError}=await admin.from("fts_selfie_print_orders").insert({event_id:event.id,guest_session_id:sessionId,paypal_environment:env,billing_mode:billingMode,payment_status:paymentStatus,print_status:"READY",unit_price_cents:0,quantity_total:quantityTotal,total_cents:0,currency:CURRENCY}).select("*").single();if(orderError)throw orderError;
      const photoMap=new Map(photos.map((p:any)=>[String(p.id),p])),itemRows=ids.map(id=>({order_id:order.id,photo_id:id,designed_path_snapshot:String(photoMap.get(id).designed_path),quantity:normalized.get(id),unit_price_cents:0,line_total_cents:0}));const {error:itemError}=await admin.from("fts_selfie_print_order_items").insert(itemRows);if(itemError){await admin.from("fts_selfie_print_orders").delete().eq("id",order.id);throw itemError}const {error:jobError}=await admin.from("fts_selfie_print_jobs").insert({print_order_id:order.id,event_id:event.id,status:"READY"});if(jobError){await admin.from("fts_selfie_print_orders").delete().eq("id",order.id);throw jobError}return json({ok:true,...safeOrderStatus(order),message:billingMode==="organizer_flat"?"Fotoprint ist vom Veranstalter übernommen":"Fotoprint ist von FTS freigegeben"});
    }

    if(action==="create-order"){
      if(billingMode!=="guest_paypal")return json({ok:false,error:"Für dieses Event ist keine Gastzahlung vorgesehen"},409);if(!configured)return json({ok:false,error:`PayPal ${env==="live"?"Live":"Sandbox"} ist serverseitig noch nicht konfiguriert`},503);
      const {normalized,ids,quantityTotal}=normalizeItems(Array.isArray(body.items)?body.items:[]),photos=await validatePhotos(admin,event.id,sessionId,ids,env),totalCents=quantityTotal*UNIT_PRICE_CENTS;
      const {data:order,error:orderError}=await admin.from("fts_selfie_print_orders").insert({event_id:event.id,guest_session_id:sessionId,paypal_environment:env,billing_mode:"guest_paypal",payment_status:"CREATED",print_status:"BLOCKED",unit_price_cents:UNIT_PRICE_CENTS,quantity_total:quantityTotal,total_cents:totalCents,currency:CURRENCY}).select("*").single();if(orderError)throw orderError;
      const photoMap=new Map(photos.map((p:any)=>[String(p.id),p])),itemRows=ids.map(id=>({order_id:order.id,photo_id:id,designed_path_snapshot:String(photoMap.get(id).designed_path),quantity:normalized.get(id),unit_price_cents:UNIT_PRICE_CENTS,line_total_cents:Number(normalized.get(id))*UNIT_PRICE_CENTS}));const {error:itemError}=await admin.from("fts_selfie_print_order_items").insert(itemRows);if(itemError){await admin.from("fts_selfie_print_orders").update({payment_status:"ERROR",last_error:"Print items insert failed"}).eq("id",order.id);throw itemError}
      try{const totalValue=centsToValue(totalCents),paypalOrder=await paypalFetch(env,"/v2/checkout/orders",{method:"POST",headers:{"PayPal-Request-Id":"fts-selfie-create-"+order.id},body:JSON.stringify({intent:"CAPTURE",purchase_units:[{reference_id:order.id,custom_id:order.id,invoice_id:"FTS-PRINT-"+order.id,description:"FTS MySelfie Fotodruck",amount:{currency_code:CURRENCY,value:totalValue,breakdown:{item_total:{currency_code:CURRENCY,value:totalValue}}},items:[{name:"MySelfie Fotoprint 10x15",quantity:String(quantityTotal),unit_amount:{currency_code:CURRENCY,value:"2.00"},category:"PHYSICAL_GOODS"}]}],payment_source:{paypal:{experience_context:{user_action:"PAY_NOW",shipping_preference:"NO_SHIPPING"}}}})});if(!paypalOrder?.id)throw new Error("PayPal Order-ID fehlt");const {error:updateError}=await admin.from("fts_selfie_print_orders").update({paypal_order_id:String(paypalOrder.id),updated_at:new Date().toISOString()}).eq("id",order.id);if(updateError)throw updateError;return json({ok:true,id:String(paypalOrder.id),orderId:String(paypalOrder.id),print_order_id:order.id,billing_mode:"guest_paypal",paypal_environment:env,quantity_total:quantityTotal,total:totalValue,total_cents:totalCents,currency:CURRENCY})}catch(e){await admin.from("fts_selfie_print_orders").update({payment_status:"ERROR",last_error:clean((e as any)?.message||e,500),updated_at:new Date().toISOString()}).eq("id",order.id);throw e}
    }

    const printOrderId=clean(body.print_order_id,80);if(!/^[0-9a-f-]{36}$/i.test(printOrderId))return json({ok:false,error:"Druckauftrag fehlt"},400);const order=await ownedOrder(admin,printOrderId,event.id,sessionId);if(!order)return json({ok:false,error:"Druckauftrag nicht gefunden"},404);const orderEnv=normalizeEnv(order.paypal_environment);
    if(action==="status"){const receipt=await receiptForOrder(admin,order.id);return json({ok:true,...safeOrderStatus(order),receipt:safeReceipt(receipt)})}
    if(action==="receipt"){if(!["COMPLETED","REFUNDED","REVERSED"].includes(order.payment_status))return json({ok:false,error:"Beleg ist nur bei eigener Gastzahlung verfügbar"},409);const receipt=await receiptForOrder(admin,order.id);if(!receipt)return json({ok:false,error:"Beleg wird noch vorbereitet"},404);return json({ok:true,receipt:safeReceipt(receipt)})}
    if(action==="cancel"){if(["COMPLETED","COVERED","FREE","REFUNDED","REVERSED"].includes(order.payment_status))return json({ok:true,...safeOrderStatus(order)});const {data:updated,error}=await admin.from("fts_selfie_print_orders").update({payment_status:"CANCELLED",print_status:"BLOCKED",cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",order.id).not("payment_status","in","(COMPLETED,COVERED,FREE,REFUNDED,REVERSED)").select("*").maybeSingle();if(error)throw error;return json({ok:true,...safeOrderStatus(updated||order)})}
    if(action==="capture-order"){
      if(order.billing_mode!=="guest_paypal")return json({ok:false,error:"Dieser Druckauftrag verwendet keine PayPal-Gastzahlung"},409);if(!(paypalClientId(orderEnv)&&paypalSecret(orderEnv)))return json({ok:false,error:`PayPal ${orderEnv==="live"?"Live":"Sandbox"} ist serverseitig noch nicht konfiguriert`},503);
      const paypalOrderId=clean(body.paypal_order_id,80);if(!paypalOrderId||paypalOrderId!==order.paypal_order_id)return json({ok:false,error:"PayPal Order-ID stimmt nicht"},400);if(order.payment_status==="COMPLETED"){const receipt=await receiptForOrder(admin,order.id);return json({ok:true,...safeOrderStatus(order),receipt:safeReceipt(receipt),idempotent:true})}if(["REFUNDED","REVERSED"].includes(order.payment_status)){const receipt=await receiptForOrder(admin,order.id);return json({ok:true,...safeOrderStatus(order),receipt:safeReceipt(receipt),idempotent:true})}
      try{let data:any;try{data=await paypalFetch(orderEnv,"/v2/checkout/orders/"+encodeURIComponent(paypalOrderId)+"/capture",{method:"POST",headers:{"PayPal-Request-Id":"fts-selfie-capture-"+order.id,"Prefer":"return=representation"},body:"{}"})}catch(captureError){try{const reconciled=await fetchPayPalOrder(orderEnv,paypalOrderId);if(paypalCapture(reconciled))data=reconciled;else throw captureError}catch{throw captureError}}const capture=paypalCapture(data),status=String(capture?.status||"").toUpperCase(),captureId=clean(capture?.id,120),amountCents=valueToCents(capture?.amount?.value),currency=clean(capture?.amount?.currency_code,10).toUpperCase();if(!captureId||!status||!Number.isFinite(amountCents)||!currency)throw new Error("PayPal Capture-Antwort unvollständig");const {data:applied,error:applyError}=await admin.rpc("fts_selfie_apply_payment_capture_v45",{p_print_order_id:order.id,p_paypal_order_id:paypalOrderId,p_capture_id:captureId,p_status:status,p_amount_cents:amountCents,p_currency:currency,p_provider_event_id:`CAPTURE_API:${captureId}:${status}`,p_event_type:"CAPTURE_API",p_verified:true,p_details:{source:"server_capture",paypal_status:status,paypal_environment:orderEnv}});if(applyError)throw applyError;const receipt=await receiptForOrder(admin,order.id);return json({ok:true,...(applied||{}),billing_mode:"guest_paypal",paypal_environment:orderEnv,receipt:safeReceipt(receipt),paypal_status:status})}catch(e){await admin.from("fts_selfie_print_orders").update({last_error:clean((e as any)?.message||e,500),updated_at:new Date().toISOString()}).eq("id",order.id);throw e}
    }
    return json({ok:false,error:"Unbekannte Aktion"},400);
  }catch(e){console.error("paypal-selfie-checkout",e);return json({ok:false,error:clean((e as any)?.message||e,500)},(e as any)?.status||500)}
});