plugins {
    id 'com.android.application'
}

android {
    namespace 'lu.fts.printer'
    compileSdk 35

    defaultConfig {
        applicationId "lu.fts.printer"
        minSdk 26
        targetSdk 35
        versionCode 81
        versionName "0.2.1-design"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-test"
        }
        release {
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
