plugins {
    id 'com.android.application'
}

android {
    namespace 'lu.fts.printer'
    compileSdk 35

    defaultConfig {
        applicationId "lu.fts.printer"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "0.1.2"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-test"
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
